- name: create new users
  hosts: 
  tasks:
     - name: create new users
       user:
         name: "{{ item }}"
         state: present
       loop:
         - kehinde
         - alex
         - oyin
